require('dotenv').config();
const mysql = require('mysql2/promise');

const pool = mysql.createPool({
    host: process.env.MYSQL_HOST,
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE,
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0
});

async function saveTelemetry(data) {
    const query = `
    INSERT INTO poc_new_bike_telemetry (
      \`timestamp\`, \`sequence\`, \`latitude\`, \`longitude\`, \`altitude\`, \`speed\`, \`satellites_visible\`, \`satellites_gps\`, \`satellites_beidou\`, \`satellites_glonass\`, \`satellites_galileo\`, \`satellites_qzss\`, \`satellites_unknown\`, \`satellites_used\`, \`fix_type\`, \`fix_status\`, \`pdop\`, \`hdop\`, \`vdop\`, \`azimuth\`, \`course\`, \`status\`, \`battery_voltage\`, \`external_voltage\`, \`gps_fix_mode\`, \`modem_app_version\`, \`modem_base_version\`, \`controller_version\`, \`imei\`, \`iccid\`, \`ble_mac\`, \`msisdn\`, \`gsm_status\`, \`gps_status\`, \`gps_ttff_s\`, \`imsi\`, \`apn\`, \`csq\`, \`internal_available_disk_size_bytes\`, \`external_available_disk_size_bytes\`, \`gps_interval_ms\`, \`imu_interval_ms\`, \`modem_uptime_ms\`, \`modem_reset_reason\`, \`num_logs\`, \`total_log_size\`, \`gps_odometer_m\`, \`can_odometer_m\`, \`rpm_odometer_m\`, \`external_battery_voltage_mv\`, \`internal_battery_voltage_mv\`, \`bluetooth_status\`, \`connected_device_name\`, \`connected_device_mac\`, \`self_mac_id\`, \`analog_input1_mv\`, \`digital_output1_status\`, \`digital_output2_status\`, \`digital_input1_status\`, \`digital_input2_status\`, \`ignition_status\`, \`charging_status\`, \`controller_uptime_s\`, \`controller_reset_reason\`, \`controller_reset_reason_unknown_count\`, \`controller_reset_reason_wko_count\`, \`controller_reset_reason_vusb_count\`, \`controller_reset_reason_wdt_count\`, \`controller_reset_reason_sw_count\`, \`can_truncated\`, \`dbc_crc32\`, \`VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info\`, \`Battery_Status_SOC\`, \`Battery_Status_Battery_Status\`, \`BatteryPack_ProdDate_Production_Day\`, \`BatteryPack_ProdDate_Production_Month\`, \`BatteryPack_ProdDate_Production_Year\`, \`Charging_Status_Realtime_Output_Current\`, \`Charging_Status_Realtime_Output_Voltage\`, \`Battery_Pack_SN_Message_Index\`, \`Battery_Pack_SN_SN_6\`, \`Battery_Pack_SN_SN_5\`, \`Battery_Pack_SN_SN_4\`, \`Battery_Pack_SN_SN_3\`, \`Battery_Pack_SN_SN_2\`, \`Battery_Pack_SN_SN_1\`, \`Battery_Pack_SN_SN_0\`, \`Charger_Status_Charger_Status\`, \`Battery_RemainingCapacity_Remaining_time_to_FullCharge\`, \`Battery_RemainingCapacity_Residual_Energy\`, \`Battery_RemainingCapacity_ResidualCapacity\`, \`Battery_RemainingCapacity_FullChargeCapacity\`, \`MCU_SYSINFO_Rated_Max_InputCurrent\`, \`MCU_SYSINFO_Rated_Voltage\`, \`MCU_SYSINFO_Rated_Speed\`, \`MCU_INFO_MCU_HW_VERSION\`, \`MCU_INFO_MCU_SW_VERSION\`, \`MCU_Data_Realtime_Current\`, \`MCU_Data_RealTime_Voltage\`, \`MCU_Data_MotorRPM\`, \`MCU_Fault_Status_MotorTemperature\`, \`MCU_Fault_Status_ControllerTemp\`, \`MCU_Fault_Status_Braking_Stroke\`, \`MCU_Fault_Status_Reverse_State\`, \`MCU_Fault_Status_CruiseState\`, \`MCU_Fault_Status_SpeedLimit_Status\`, \`MCU_Fault_Status_Immobilization_Status\`, \`MCU_Fault_Status_Brake_Status\`, \`MCU_Fault_Status_Veh_Mode\`, \`MCU_Fault_Status_Disabled_State\`, \`MCU_Fault_Status_Charging_Protection_Status\`, \`MCU_Fault_Status_Ready_Status\`, \`MCU_Fault_Status_EBS_Status\`, \`MCU_Fault_Status_MotorHall_Failure\`, \`MCU_Fault_Status_MotorPhase_failure\`, \`MCU_Fault_Status_Overtemp_Fault\`, \`MCU_Fault_Status_UnderVoltage_Fault\`, \`MCU_Fault_Status_OverCurrent_Fault\`, \`MCU_Fault_Status_Driver_Failure\`, \`MCU_Fault_Status_MOSFET_Failure\`, \`MCU_Fault_Status_Motor_Controller_RunStatus\`, \`MCU_Fault_Status_Throttle_Failure\`, \`MCU_Fault_Status_Motor_Overtemp_Fault\`, \`Battery_Pack_Fault_Info_Discharge_Protection_State\`, \`Battery_Pack_Fault_Info_Charge_Protection_State\`, \`Battery_Pack_Fault_Info_Severe_OverCell_Voltage\`, \`Battery_Pack_Fault_Info_EOL_State\`, \`Battery_Pack_Fault_Info_Charge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_Charge_MOSFail\`, \`Battery_Pack_Fault_Info_Discharge_MOSFail\`, \`Battery_Pack_Fault_Info_PreDischarge_MOSFail\`, \`Battery_Pack_Fault_Info_ZeroVoltage_Protection\`, \`Battery_Pack_Fault_Info_FullyCharge\`, \`Battery_Pack_Fault_Info_MOS_OverTemp\`, \`Battery_Pack_Fault_Info_OverTemp_Balance_Resistance\`, \`Battery_Pack_Fault_Info_PreDischarge_Timeout\`, \`Battery_Pack_Fault_Info_PreDischarge_OverCurrent\`, \`Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp\`, \`Battery_Pack_Fault_Info_Temp_Acquisition_Fault\`, \`Battery_Pack_Fault_Info_Batt_ID_Conflict\`, \`Battery_Pack_Fault_Info_Discharge_Over_Plus_Current\`, \`Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault\`, \`Battery_Pack_Fault_Info_Discharge_Over_Current\`, \`Battery_Pack_Fault_Info_Regen_Over_Current\`, \`Battery_Pack_Fault_Info_Charging_OverTemp_Current\`, \`Battery_Pack_Fault_Info_High_Differential_Cell_Temp\`, \`Battery_Pack_Fault_Info_Charging_Low_Temp\`, \`Battery_Pack_Fault_Info_Charging_Over_Temp\`, \`Battery_Pack_Fault_Info_Discharge_Low_Temp\`, \`Battery_Pack_Fault_Info_Discharge_Over_Temp\`, \`Battery_Pack_Fault_Info_Pack_Under_Voltage\`, \`Battery_Pack_Fault_Info_Pack_Over_Voltage\`, \`Battery_Pack_Fault_Info_Cell_Under_Voltage\`, \`Battery_Pack_Fault_Info_Cell_Over_Voltage\`, \`Battery_Pack_Temp_info_Battery_Ambient_Temp\`, \`Battery_Pack_Temp_info_Battery_MOS_Temp_Max\`, \`Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum\`, \`Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum\`, \`Battery_SOC_Info_State_of_Health_SOH\`, \`Battery_SOC_Info_Num_of_Battery_Cycles\`, \`Battery_SOC_Info_State_of_Charge_SOC\`, \`Battery_Voltage_MOS_Info_ON_Signal_Status\`, \`Battery_Voltage_MOS_Info_CRG_Signal_Status\`, \`Battery_Voltage_MOS_Info_ACC_Signal_Status\`, \`Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Charging_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Current\`, \`Battery_Voltage_MOS_Info_Battery_Voltage\`, \`Battery_Voltage_Current_Info_Remaining_time_to_charge\`, \`Battery_Voltage_Current_Info_Total_Battery_Current\`, \`Battery_Voltage_Current_Info_Total_Battery_Voltage\`, \`RTC_RTC_seconds\`, \`RTC_RTC_Minutes\`, \`RTC_RTC_Hours\`, \`RTC_RTC_Days\`, \`RTC_RTC_Years\`, \`RTC_RTC_Months\`, \`Battery_Pack_Temp_Temperature_6\`, \`Battery_Pack_Temp_Temperature_5\`, \`Battery_Pack_Temp_Temperature_4\`, \`Battery_Pack_Temp_Temperature_3\`, \`Battery_Pack_Temp_Temperature_2\`, \`Battery_Pack_Temp_Temperature_1\`, \`Battery_Pack_Temp_Temperature_0\`, \`Battery_Pack_Temp_Number_of_Temperatues\`, \`Battery_Pack_Temp_Msg_Number_Index\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell\`, \`Cell_Voltage_Info_Num_of_cells\`, \`Cell_Voltage_Info_Message_Number_Index\`, \`Cell_Voltage_Minimum_Voltage\`, \`Cell_Voltage_Maximum_Voltage\`, \`Charge_discharge_Operating_State_Battery7\`, \`Charge_discharge_Opearting_State_Battery6\`, \`Charge_discharge_Operating_State_Battery5\`, \`Charge_discharge_Operating_state_Battery4\`, \`Charge_discharge_Operating_State_battery3\`, \`Charge_discharge_Operating_state_battery2\`, \`Charge_discharge_Operating_state_battery1\`, \`Charge_discharge_Battery0_Working_State\`, \`Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery\`, \`Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery\`, \`SOP_Info_Battery_Pack_Total_Battery_Discharge_Current\`, \`SOP_Info_Battery_Pack_Continuous_Discharge_Current\`, \`SOP_Info_Battery_Pack_Operating_state_Battery4\`, \`events_dropped\`, \`event_timestamp_ms\`, \`event_data_name\`, \`event_data_value\`
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `;

    const values = [
        data['timestamp'] !== undefined ? data['timestamp'] : null,
        data['sequence'] !== undefined ? data['sequence'] : null,
        data['latitude'] !== undefined ? data['latitude'] : null,
        data['longitude'] !== undefined ? data['longitude'] : null,
        data['altitude'] !== undefined ? data['altitude'] : null,
        data['speed'] !== undefined ? data['speed'] : null,
        data['satellites_visible'] !== undefined ? data['satellites_visible'] : null,
        data['satellites_gps'] !== undefined ? data['satellites_gps'] : null,
        data['satellites_beidou'] !== undefined ? data['satellites_beidou'] : null,
        data['satellites_glonass'] !== undefined ? data['satellites_glonass'] : null,
        data['satellites_galileo'] !== undefined ? data['satellites_galileo'] : null,
        data['satellites_qzss'] !== undefined ? data['satellites_qzss'] : null,
        data['satellites_unknown'] !== undefined ? data['satellites_unknown'] : null,
        data['satellites_used'] !== undefined ? data['satellites_used'] : null,
        data['fix_type'] !== undefined ? data['fix_type'] : null,
        data['fix_status'] !== undefined ? data['fix_status'] : null,
        data['pdop'] !== undefined ? data['pdop'] : null,
        data['hdop'] !== undefined ? data['hdop'] : null,
        data['vdop'] !== undefined ? data['vdop'] : null,
        data['azimuth'] !== undefined ? data['azimuth'] : null,
        data['course'] !== undefined ? data['course'] : null,
        data['status'] !== undefined ? data['status'] : null,
        data['battery_voltage'] !== undefined ? data['battery_voltage'] : null,
        data['external_voltage'] !== undefined ? data['external_voltage'] : null,
        data['gps_fix_mode'] !== undefined ? data['gps_fix_mode'] : null,
        data['modem_app_version'] !== undefined ? data['modem_app_version'] : null,
        data['modem_base_version'] !== undefined ? data['modem_base_version'] : null,
        data['controller_version'] !== undefined ? data['controller_version'] : null,
        data['imei'] !== undefined ? data['imei'] : null,
        data['iccid'] !== undefined ? data['iccid'] : null,
        data['ble_mac'] !== undefined ? data['ble_mac'] : null,
        data['msisdn'] !== undefined ? data['msisdn'] : null,
        data['gsm_status'] !== undefined ? data['gsm_status'] : null,
        data['gps_status'] !== undefined ? data['gps_status'] : null,
        data['gps_ttff_s'] !== undefined ? data['gps_ttff_s'] : null,
        data['imsi'] !== undefined ? data['imsi'] : null,
        data['apn'] !== undefined ? data['apn'] : null,
        data['csq'] !== undefined ? data['csq'] : null,
        data['internal_available_disk_size_bytes'] !== undefined ? data['internal_available_disk_size_bytes'] : null,
        data['external_available_disk_size_bytes'] !== undefined ? data['external_available_disk_size_bytes'] : null,
        data['gps_interval_ms'] !== undefined ? data['gps_interval_ms'] : null,
        data['imu_interval_ms'] !== undefined ? data['imu_interval_ms'] : null,
        data['modem_uptime_ms'] !== undefined ? data['modem_uptime_ms'] : null,
        data['modem_reset_reason'] !== undefined ? data['modem_reset_reason'] : null,
        data['num_logs'] !== undefined ? data['num_logs'] : null,
        data['total_log_size'] !== undefined ? data['total_log_size'] : null,
        data['gps_odometer_m'] !== undefined ? data['gps_odometer_m'] : null,
        data['can_odometer_m'] !== undefined ? data['can_odometer_m'] : null,
        data['rpm_odometer_m'] !== undefined ? data['rpm_odometer_m'] : null,
        data['external_battery_voltage_mv'] !== undefined ? data['external_battery_voltage_mv'] : null,
        data['internal_battery_voltage_mv'] !== undefined ? data['internal_battery_voltage_mv'] : null,
        data['bluetooth_status'] !== undefined ? data['bluetooth_status'] : null,
        data['connected_device_name'] !== undefined ? data['connected_device_name'] : null,
        data['connected_device_mac'] !== undefined ? data['connected_device_mac'] : null,
        data['self_mac_id'] !== undefined ? data['self_mac_id'] : null,
        data['analog_input1_mv'] !== undefined ? data['analog_input1_mv'] : null,
        data['digital_output1_status'] !== undefined ? data['digital_output1_status'] : null,
        data['digital_output2_status'] !== undefined ? data['digital_output2_status'] : null,
        data['digital_input1_status'] !== undefined ? data['digital_input1_status'] : null,
        data['digital_input2_status'] !== undefined ? data['digital_input2_status'] : null,
        data['ignition_status'] !== undefined ? data['ignition_status'] : null,
        data['charging_status'] !== undefined ? data['charging_status'] : null,
        data['controller_uptime_s'] !== undefined ? data['controller_uptime_s'] : null,
        data['controller_reset_reason'] !== undefined ? data['controller_reset_reason'] : null,
        data['controller_reset_reason_unknown_count'] !== undefined ? data['controller_reset_reason_unknown_count'] : null,
        data['controller_reset_reason_wko_count'] !== undefined ? data['controller_reset_reason_wko_count'] : null,
        data['controller_reset_reason_vusb_count'] !== undefined ? data['controller_reset_reason_vusb_count'] : null,
        data['controller_reset_reason_wdt_count'] !== undefined ? data['controller_reset_reason_wdt_count'] : null,
        data['controller_reset_reason_sw_count'] !== undefined ? data['controller_reset_reason_sw_count'] : null,
        data['can_truncated'] !== undefined ? data['can_truncated'] : null,
        data['dbc_crc32'] !== undefined ? data['dbc_crc32'] : null,
        data['VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info'] !== undefined ? data['VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info'] : null,
        data['Battery_Status_SOC'] !== undefined ? data['Battery_Status_SOC'] : null,
        data['Battery_Status_Battery_Status'] !== undefined ? data['Battery_Status_Battery_Status'] : null,
        data['BatteryPack_ProdDate_Production_Day'] !== undefined ? data['BatteryPack_ProdDate_Production_Day'] : null,
        data['BatteryPack_ProdDate_Production_Month'] !== undefined ? data['BatteryPack_ProdDate_Production_Month'] : null,
        data['BatteryPack_ProdDate_Production_Year'] !== undefined ? data['BatteryPack_ProdDate_Production_Year'] : null,
        data['Charging_Status_Realtime_Output_Current'] !== undefined ? data['Charging_Status_Realtime_Output_Current'] : null,
        data['Charging_Status_Realtime_Output_Voltage'] !== undefined ? data['Charging_Status_Realtime_Output_Voltage'] : null,
        data['Battery_Pack_SN_Message_Index'] !== undefined ? data['Battery_Pack_SN_Message_Index'] : null,
        data['Battery_Pack_SN_SN_6'] !== undefined ? data['Battery_Pack_SN_SN_6'] : null,
        data['Battery_Pack_SN_SN_5'] !== undefined ? data['Battery_Pack_SN_SN_5'] : null,
        data['Battery_Pack_SN_SN_4'] !== undefined ? data['Battery_Pack_SN_SN_4'] : null,
        data['Battery_Pack_SN_SN_3'] !== undefined ? data['Battery_Pack_SN_SN_3'] : null,
        data['Battery_Pack_SN_SN_2'] !== undefined ? data['Battery_Pack_SN_SN_2'] : null,
        data['Battery_Pack_SN_SN_1'] !== undefined ? data['Battery_Pack_SN_SN_1'] : null,
        data['Battery_Pack_SN_SN_0'] !== undefined ? data['Battery_Pack_SN_SN_0'] : null,
        data['Charger_Status_Charger_Status'] !== undefined ? data['Charger_Status_Charger_Status'] : null,
        data['Battery_RemainingCapacity_Remaining_time_to_FullCharge'] !== undefined ? data['Battery_RemainingCapacity_Remaining_time_to_FullCharge'] : null,
        data['Battery_RemainingCapacity_Residual_Energy'] !== undefined ? data['Battery_RemainingCapacity_Residual_Energy'] : null,
        data['Battery_RemainingCapacity_ResidualCapacity'] !== undefined ? data['Battery_RemainingCapacity_ResidualCapacity'] : null,
        data['Battery_RemainingCapacity_FullChargeCapacity'] !== undefined ? data['Battery_RemainingCapacity_FullChargeCapacity'] : null,
        data['MCU_SYSINFO_Rated_Max_InputCurrent'] !== undefined ? data['MCU_SYSINFO_Rated_Max_InputCurrent'] : null,
        data['MCU_SYSINFO_Rated_Voltage'] !== undefined ? data['MCU_SYSINFO_Rated_Voltage'] : null,
        data['MCU_SYSINFO_Rated_Speed'] !== undefined ? data['MCU_SYSINFO_Rated_Speed'] : null,
        data['MCU_INFO_MCU_HW_VERSION'] !== undefined ? data['MCU_INFO_MCU_HW_VERSION'] : null,
        data['MCU_INFO_MCU_SW_VERSION'] !== undefined ? data['MCU_INFO_MCU_SW_VERSION'] : null,
        data['MCU_Data_Realtime_Current'] !== undefined ? data['MCU_Data_Realtime_Current'] : null,
        data['MCU_Data_RealTime_Voltage'] !== undefined ? data['MCU_Data_RealTime_Voltage'] : null,
        data['MCU_Data_MotorRPM'] !== undefined ? data['MCU_Data_MotorRPM'] : null,
        data['MCU_Fault_Status_MotorTemperature'] !== undefined ? data['MCU_Fault_Status_MotorTemperature'] : null,
        data['MCU_Fault_Status_ControllerTemp'] !== undefined ? data['MCU_Fault_Status_ControllerTemp'] : null,
        data['MCU_Fault_Status_Braking_Stroke'] !== undefined ? data['MCU_Fault_Status_Braking_Stroke'] : null,
        data['MCU_Fault_Status_Reverse_State'] !== undefined ? data['MCU_Fault_Status_Reverse_State'] : null,
        data['MCU_Fault_Status_CruiseState'] !== undefined ? data['MCU_Fault_Status_CruiseState'] : null,
        data['MCU_Fault_Status_SpeedLimit_Status'] !== undefined ? data['MCU_Fault_Status_SpeedLimit_Status'] : null,
        data['MCU_Fault_Status_Immobilization_Status'] !== undefined ? data['MCU_Fault_Status_Immobilization_Status'] : null,
        data['MCU_Fault_Status_Brake_Status'] !== undefined ? data['MCU_Fault_Status_Brake_Status'] : null,
        data['MCU_Fault_Status_Veh_Mode'] !== undefined ? data['MCU_Fault_Status_Veh_Mode'] : null,
        data['MCU_Fault_Status_Disabled_State'] !== undefined ? data['MCU_Fault_Status_Disabled_State'] : null,
        data['MCU_Fault_Status_Charging_Protection_Status'] !== undefined ? data['MCU_Fault_Status_Charging_Protection_Status'] : null,
        data['MCU_Fault_Status_Ready_Status'] !== undefined ? data['MCU_Fault_Status_Ready_Status'] : null,
        data['MCU_Fault_Status_EBS_Status'] !== undefined ? data['MCU_Fault_Status_EBS_Status'] : null,
        data['MCU_Fault_Status_MotorHall_Failure'] !== undefined ? data['MCU_Fault_Status_MotorHall_Failure'] : null,
        data['MCU_Fault_Status_MotorPhase_failure'] !== undefined ? data['MCU_Fault_Status_MotorPhase_failure'] : null,
        data['MCU_Fault_Status_Overtemp_Fault'] !== undefined ? data['MCU_Fault_Status_Overtemp_Fault'] : null,
        data['MCU_Fault_Status_UnderVoltage_Fault'] !== undefined ? data['MCU_Fault_Status_UnderVoltage_Fault'] : null,
        data['MCU_Fault_Status_OverCurrent_Fault'] !== undefined ? data['MCU_Fault_Status_OverCurrent_Fault'] : null,
        data['MCU_Fault_Status_Driver_Failure'] !== undefined ? data['MCU_Fault_Status_Driver_Failure'] : null,
        data['MCU_Fault_Status_MOSFET_Failure'] !== undefined ? data['MCU_Fault_Status_MOSFET_Failure'] : null,
        data['MCU_Fault_Status_Motor_Controller_RunStatus'] !== undefined ? data['MCU_Fault_Status_Motor_Controller_RunStatus'] : null,
        data['MCU_Fault_Status_Throttle_Failure'] !== undefined ? data['MCU_Fault_Status_Throttle_Failure'] : null,
        data['MCU_Fault_Status_Motor_Overtemp_Fault'] !== undefined ? data['MCU_Fault_Status_Motor_Overtemp_Fault'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Protection_State'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Protection_State'] : null,
        data['Battery_Pack_Fault_Info_Charge_Protection_State'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_Protection_State'] : null,
        data['Battery_Pack_Fault_Info_Severe_OverCell_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Severe_OverCell_Voltage'] : null,
        data['Battery_Pack_Fault_Info_EOL_State'] !== undefined ? data['Battery_Pack_Fault_Info_EOL_State'] : null,
        data['Battery_Pack_Fault_Info_Charge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_Charge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_Discharge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_ZeroVoltage_Protection'] !== undefined ? data['Battery_Pack_Fault_Info_ZeroVoltage_Protection'] : null,
        data['Battery_Pack_Fault_Info_FullyCharge'] !== undefined ? data['Battery_Pack_Fault_Info_FullyCharge'] : null,
        data['Battery_Pack_Fault_Info_MOS_OverTemp'] !== undefined ? data['Battery_Pack_Fault_Info_MOS_OverTemp'] : null,
        data['Battery_Pack_Fault_Info_OverTemp_Balance_Resistance'] !== undefined ? data['Battery_Pack_Fault_Info_OverTemp_Balance_Resistance'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_Timeout'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_Timeout'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_OverCurrent'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_OverCurrent'] : null,
        data['Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp'] !== undefined ? data['Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp'] : null,
        data['Battery_Pack_Fault_Info_Temp_Acquisition_Fault'] !== undefined ? data['Battery_Pack_Fault_Info_Temp_Acquisition_Fault'] : null,
        data['Battery_Pack_Fault_Info_Batt_ID_Conflict'] !== undefined ? data['Battery_Pack_Fault_Info_Batt_ID_Conflict'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Plus_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Plus_Current'] : null,
        data['Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Current'] : null,
        data['Battery_Pack_Fault_Info_Regen_Over_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Regen_Over_Current'] : null,
        data['Battery_Pack_Fault_Info_Charging_OverTemp_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_OverTemp_Current'] : null,
        data['Battery_Pack_Fault_Info_High_Differential_Cell_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_High_Differential_Cell_Temp'] : null,
        data['Battery_Pack_Fault_Info_Charging_Low_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_Low_Temp'] : null,
        data['Battery_Pack_Fault_Info_Charging_Over_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_Over_Temp'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Low_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Low_Temp'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Temp'] : null,
        data['Battery_Pack_Fault_Info_Pack_Under_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Pack_Under_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Pack_Over_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Pack_Over_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Cell_Under_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Under_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Cell_Over_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Over_Voltage'] : null,
        data['Battery_Pack_Temp_info_Battery_Ambient_Temp'] !== undefined ? data['Battery_Pack_Temp_info_Battery_Ambient_Temp'] : null,
        data['Battery_Pack_Temp_info_Battery_MOS_Temp_Max'] !== undefined ? data['Battery_Pack_Temp_info_Battery_MOS_Temp_Max'] : null,
        data['Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum'] !== undefined ? data['Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum'] : null,
        data['Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum'] !== undefined ? data['Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum'] : null,
        data['Battery_SOC_Info_State_of_Health_SOH'] !== undefined ? data['Battery_SOC_Info_State_of_Health_SOH'] : null,
        data['Battery_SOC_Info_Num_of_Battery_Cycles'] !== undefined ? data['Battery_SOC_Info_Num_of_Battery_Cycles'] : null,
        data['Battery_SOC_Info_State_of_Charge_SOC'] !== undefined ? data['Battery_SOC_Info_State_of_Charge_SOC'] : null,
        data['Battery_Voltage_MOS_Info_ON_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_ON_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_CRG_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_CRG_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_ACC_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_ACC_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Charging_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Charging_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Current'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Current'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Voltage'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Voltage'] : null,
        data['Battery_Voltage_Current_Info_Remaining_time_to_charge'] !== undefined ? data['Battery_Voltage_Current_Info_Remaining_time_to_charge'] : null,
        data['Battery_Voltage_Current_Info_Total_Battery_Current'] !== undefined ? data['Battery_Voltage_Current_Info_Total_Battery_Current'] : null,
        data['Battery_Voltage_Current_Info_Total_Battery_Voltage'] !== undefined ? data['Battery_Voltage_Current_Info_Total_Battery_Voltage'] : null,
        data['RTC_RTC_seconds'] !== undefined ? data['RTC_RTC_seconds'] : null,
        data['RTC_RTC_Minutes'] !== undefined ? data['RTC_RTC_Minutes'] : null,
        data['RTC_RTC_Hours'] !== undefined ? data['RTC_RTC_Hours'] : null,
        data['RTC_RTC_Days'] !== undefined ? data['RTC_RTC_Days'] : null,
        data['RTC_RTC_Years'] !== undefined ? data['RTC_RTC_Years'] : null,
        data['RTC_RTC_Months'] !== undefined ? data['RTC_RTC_Months'] : null,
        data['Battery_Pack_Temp_Temperature_6'] !== undefined ? data['Battery_Pack_Temp_Temperature_6'] : null,
        data['Battery_Pack_Temp_Temperature_5'] !== undefined ? data['Battery_Pack_Temp_Temperature_5'] : null,
        data['Battery_Pack_Temp_Temperature_4'] !== undefined ? data['Battery_Pack_Temp_Temperature_4'] : null,
        data['Battery_Pack_Temp_Temperature_3'] !== undefined ? data['Battery_Pack_Temp_Temperature_3'] : null,
        data['Battery_Pack_Temp_Temperature_2'] !== undefined ? data['Battery_Pack_Temp_Temperature_2'] : null,
        data['Battery_Pack_Temp_Temperature_1'] !== undefined ? data['Battery_Pack_Temp_Temperature_1'] : null,
        data['Battery_Pack_Temp_Temperature_0'] !== undefined ? data['Battery_Pack_Temp_Temperature_0'] : null,
        data['Battery_Pack_Temp_Number_of_Temperatues'] !== undefined ? data['Battery_Pack_Temp_Number_of_Temperatues'] : null,
        data['Battery_Pack_Temp_Msg_Number_Index'] !== undefined ? data['Battery_Pack_Temp_Msg_Number_Index'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell'] : null,
        data['Cell_Voltage_Info_Num_of_cells'] !== undefined ? data['Cell_Voltage_Info_Num_of_cells'] : null,
        data['Cell_Voltage_Info_Message_Number_Index'] !== undefined ? data['Cell_Voltage_Info_Message_Number_Index'] : null,
        data['Cell_Voltage_Minimum_Voltage'] !== undefined ? data['Cell_Voltage_Minimum_Voltage'] : null,
        data['Cell_Voltage_Maximum_Voltage'] !== undefined ? data['Cell_Voltage_Maximum_Voltage'] : null,
        data['Charge_discharge_Operating_State_Battery7'] !== undefined ? data['Charge_discharge_Operating_State_Battery7'] : null,
        data['Charge_discharge_Opearting_State_Battery6'] !== undefined ? data['Charge_discharge_Opearting_State_Battery6'] : null,
        data['Charge_discharge_Operating_State_Battery5'] !== undefined ? data['Charge_discharge_Operating_State_Battery5'] : null,
        data['Charge_discharge_Operating_state_Battery4'] !== undefined ? data['Charge_discharge_Operating_state_Battery4'] : null,
        data['Charge_discharge_Operating_State_battery3'] !== undefined ? data['Charge_discharge_Operating_State_battery3'] : null,
        data['Charge_discharge_Operating_state_battery2'] !== undefined ? data['Charge_discharge_Operating_state_battery2'] : null,
        data['Charge_discharge_Operating_state_battery1'] !== undefined ? data['Charge_discharge_Operating_state_battery1'] : null,
        data['Charge_discharge_Battery0_Working_State'] !== undefined ? data['Charge_discharge_Battery0_Working_State'] : null,
        data['Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery'] !== undefined ? data['Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery'] : null,
        data['Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery'] !== undefined ? data['Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery'] : null,
        data['SOP_Info_Battery_Pack_Total_Battery_Discharge_Current'] !== undefined ? data['SOP_Info_Battery_Pack_Total_Battery_Discharge_Current'] : null,
        data['SOP_Info_Battery_Pack_Continuous_Discharge_Current'] !== undefined ? data['SOP_Info_Battery_Pack_Continuous_Discharge_Current'] : null,
        data['SOP_Info_Battery_Pack_Operating_state_Battery4'] !== undefined ? data['SOP_Info_Battery_Pack_Operating_state_Battery4'] : null,
        data['events_dropped'] !== undefined ? data['events_dropped'] : null,
        data['event_timestamp_ms'] !== undefined ? data['event_timestamp_ms'] : null,
        data['event_data_name'] !== undefined ? data['event_data_name'] : null,
        data['event_data_value'] !== undefined ? data['event_data_value'] : null
    ];

    try {
        const [result] = await pool.query(query, values);
        console.log(`Telemetry saved for IMEI: ${data.imei}, Sequence: ${data.sequence}`);
        return result;
    } catch (error) {
        console.error('Error saving telemetry:', error);
        throw error;
    }
}

async function isDuplicate(imei, sequence) {
    const query = 'SELECT id FROM poc_new_bike_telemetry WHERE imei = ? AND sequence = ? LIMIT 1';
    const [rows] = await pool.query(query, [imei, sequence]);
    return rows.length > 0;
}



async function saveTelemetryBulk(dataArray) {
    if (!dataArray || dataArray.length === 0) return;

    const query = `
    INSERT INTO poc_new_bike_telemetry (
      \`timestamp\`, \`sequence\`, \`latitude\`, \`longitude\`, \`altitude\`, \`speed\`, \`satellites_visible\`, \`satellites_gps\`, \`satellites_beidou\`, \`satellites_glonass\`, \`satellites_galileo\`, \`satellites_qzss\`, \`satellites_unknown\`, \`satellites_used\`, \`fix_type\`, \`fix_status\`, \`pdop\`, \`hdop\`, \`vdop\`, \`azimuth\`, \`course\`, \`status\`, \`battery_voltage\`, \`external_voltage\`, \`gps_fix_mode\`, \`modem_app_version\`, \`modem_base_version\`, \`controller_version\`, \`imei\`, \`iccid\`, \`ble_mac\`, \`msisdn\`, \`gsm_status\`, \`gps_status\`, \`gps_ttff_s\`, \`imsi\`, \`apn\`, \`csq\`, \`internal_available_disk_size_bytes\`, \`external_available_disk_size_bytes\`, \`gps_interval_ms\`, \`imu_interval_ms\`, \`modem_uptime_ms\`, \`modem_reset_reason\`, \`num_logs\`, \`total_log_size\`, \`gps_odometer_m\`, \`can_odometer_m\`, \`rpm_odometer_m\`, \`external_battery_voltage_mv\`, \`internal_battery_voltage_mv\`, \`bluetooth_status\`, \`connected_device_name\`, \`connected_device_mac\`, \`self_mac_id\`, \`analog_input1_mv\`, \`digital_output1_status\`, \`digital_output2_status\`, \`digital_input1_status\`, \`digital_input2_status\`, \`ignition_status\`, \`charging_status\`, \`controller_uptime_s\`, \`controller_reset_reason\`, \`controller_reset_reason_unknown_count\`, \`controller_reset_reason_wko_count\`, \`controller_reset_reason_vusb_count\`, \`controller_reset_reason_wdt_count\`, \`controller_reset_reason_sw_count\`, \`can_truncated\`, \`dbc_crc32\`, \`VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info\`, \`Battery_Status_SOC\`, \`Battery_Status_Battery_Status\`, \`BatteryPack_ProdDate_Production_Day\`, \`BatteryPack_ProdDate_Production_Month\`, \`BatteryPack_ProdDate_Production_Year\`, \`Charging_Status_Realtime_Output_Current\`, \`Charging_Status_Realtime_Output_Voltage\`, \`Battery_Pack_SN_Message_Index\`, \`Battery_Pack_SN_SN_6\`, \`Battery_Pack_SN_SN_5\`, \`Battery_Pack_SN_SN_4\`, \`Battery_Pack_SN_SN_3\`, \`Battery_Pack_SN_SN_2\`, \`Battery_Pack_SN_SN_1\`, \`Battery_Pack_SN_SN_0\`, \`Charger_Status_Charger_Status\`, \`Battery_RemainingCapacity_Remaining_time_to_FullCharge\`, \`Battery_RemainingCapacity_Residual_Energy\`, \`Battery_RemainingCapacity_ResidualCapacity\`, \`Battery_RemainingCapacity_FullChargeCapacity\`, \`MCU_SYSINFO_Rated_Max_InputCurrent\`, \`MCU_SYSINFO_Rated_Voltage\`, \`MCU_SYSINFO_Rated_Speed\`, \`MCU_INFO_MCU_HW_VERSION\`, \`MCU_INFO_MCU_SW_VERSION\`, \`MCU_Data_Realtime_Current\`, \`MCU_Data_RealTime_Voltage\`, \`MCU_Data_MotorRPM\`, \`MCU_Fault_Status_MotorTemperature\`, \`MCU_Fault_Status_ControllerTemp\`, \`MCU_Fault_Status_Braking_Stroke\`, \`MCU_Fault_Status_Reverse_State\`, \`MCU_Fault_Status_CruiseState\`, \`MCU_Fault_Status_SpeedLimit_Status\`, \`MCU_Fault_Status_Immobilization_Status\`, \`MCU_Fault_Status_Brake_Status\`, \`MCU_Fault_Status_Veh_Mode\`, \`MCU_Fault_Status_Disabled_State\`, \`MCU_Fault_Status_Charging_Protection_Status\`, \`MCU_Fault_Status_Ready_Status\`, \`MCU_Fault_Status_EBS_Status\`, \`MCU_Fault_Status_MotorHall_Failure\`, \`MCU_Fault_Status_MotorPhase_failure\`, \`MCU_Fault_Status_Overtemp_Fault\`, \`MCU_Fault_Status_UnderVoltage_Fault\`, \`MCU_Fault_Status_OverCurrent_Fault\`, \`MCU_Fault_Status_Driver_Failure\`, \`MCU_Fault_Status_MOSFET_Failure\`, \`MCU_Fault_Status_Motor_Controller_RunStatus\`, \`MCU_Fault_Status_Throttle_Failure\`, \`MCU_Fault_Status_Motor_Overtemp_Fault\`, \`Battery_Pack_Fault_Info_Discharge_Protection_State\`, \`Battery_Pack_Fault_Info_Charge_Protection_State\`, \`Battery_Pack_Fault_Info_Severe_OverCell_Voltage\`, \`Battery_Pack_Fault_Info_EOL_State\`, \`Battery_Pack_Fault_Info_Charge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail\`, \`Battery_Pack_Fault_Info_Charge_MOSFail\`, \`Battery_Pack_Fault_Info_Discharge_MOSFail\`, \`Battery_Pack_Fault_Info_PreDischarge_MOSFail\`, \`Battery_Pack_Fault_Info_ZeroVoltage_Protection\`, \`Battery_Pack_Fault_Info_FullyCharge\`, \`Battery_Pack_Fault_Info_MOS_OverTemp\`, \`Battery_Pack_Fault_Info_OverTemp_Balance_Resistance\`, \`Battery_Pack_Fault_Info_PreDischarge_Timeout\`, \`Battery_Pack_Fault_Info_PreDischarge_OverCurrent\`, \`Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp\`, \`Battery_Pack_Fault_Info_Temp_Acquisition_Fault\`, \`Battery_Pack_Fault_Info_Batt_ID_Conflict\`, \`Battery_Pack_Fault_Info_Discharge_Over_Plus_Current\`, \`Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault\`, \`Battery_Pack_Fault_Info_Discharge_Over_Current\`, \`Battery_Pack_Fault_Info_Regen_Over_Current\`, \`Battery_Pack_Fault_Info_Charging_OverTemp_Current\`, \`Battery_Pack_Fault_Info_High_Differential_Cell_Temp\`, \`Battery_Pack_Fault_Info_Charging_Low_Temp\`, \`Battery_Pack_Fault_Info_Charging_Over_Temp\`, \`Battery_Pack_Fault_Info_Discharge_Low_Temp\`, \`Battery_Pack_Fault_Info_Discharge_Over_Temp\`, \`Battery_Pack_Fault_Info_Pack_Under_Voltage\`, \`Battery_Pack_Fault_Info_Pack_Over_Voltage\`, \`Battery_Pack_Fault_Info_Cell_Under_Voltage\`, \`Battery_Pack_Fault_Info_Cell_Over_Voltage\`, \`Battery_Pack_Temp_info_Battery_Ambient_Temp\`, \`Battery_Pack_Temp_info_Battery_MOS_Temp_Max\`, \`Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum\`, \`Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum\`, \`Battery_SOC_Info_State_of_Health_SOH\`, \`Battery_SOC_Info_Num_of_Battery_Cycles\`, \`Battery_SOC_Info_State_of_Charge_SOC\`, \`Battery_Voltage_MOS_Info_ON_Signal_Status\`, \`Battery_Voltage_MOS_Info_CRG_Signal_Status\`, \`Battery_Voltage_MOS_Info_ACC_Signal_Status\`, \`Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Charging_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State\`, \`Battery_Voltage_MOS_Info_Battery_Current\`, \`Battery_Voltage_MOS_Info_Battery_Voltage\`, \`Battery_Voltage_Current_Info_Remaining_time_to_charge\`, \`Battery_Voltage_Current_Info_Total_Battery_Current\`, \`Battery_Voltage_Current_Info_Total_Battery_Voltage\`, \`RTC_RTC_seconds\`, \`RTC_RTC_Minutes\`, \`RTC_RTC_Hours\`, \`RTC_RTC_Days\`, \`RTC_RTC_Years\`, \`RTC_RTC_Months\`, \`Battery_Pack_Temp_Temperature_6\`, \`Battery_Pack_Temp_Temperature_5\`, \`Battery_Pack_Temp_Temperature_4\`, \`Battery_Pack_Temp_Temperature_3\`, \`Battery_Pack_Temp_Temperature_2\`, \`Battery_Pack_Temp_Temperature_1\`, \`Battery_Pack_Temp_Temperature_0\`, \`Battery_Pack_Temp_Number_of_Temperatues\`, \`Battery_Pack_Temp_Msg_Number_Index\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell\`, \`Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell\`, \`Cell_Voltage_Info_Num_of_cells\`, \`Cell_Voltage_Info_Message_Number_Index\`, \`Cell_Voltage_Minimum_Voltage\`, \`Cell_Voltage_Maximum_Voltage\`, \`Charge_discharge_Operating_State_Battery7\`, \`Charge_discharge_Opearting_State_Battery6\`, \`Charge_discharge_Operating_State_Battery5\`, \`Charge_discharge_Operating_state_Battery4\`, \`Charge_discharge_Operating_State_battery3\`, \`Charge_discharge_Operating_state_battery2\`, \`Charge_discharge_Operating_state_battery1\`, \`Charge_discharge_Battery0_Working_State\`, \`Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery\`, \`Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery\`, \`SOP_Info_Battery_Pack_Total_Battery_Discharge_Current\`, \`SOP_Info_Battery_Pack_Continuous_Discharge_Current\`, \`SOP_Info_Battery_Pack_Operating_state_Battery4\`, \`events_dropped\`, \`event_timestamp_ms\`, \`event_data_name\`, \`event_data_value\`
    ) VALUES ?
  `;

    const valuesArray = dataArray.map(data => [
        data['timestamp'] !== undefined ? data['timestamp'] : null,
        data['sequence'] !== undefined ? data['sequence'] : null,
        data['latitude'] !== undefined ? data['latitude'] : null,
        data['longitude'] !== undefined ? data['longitude'] : null,
        data['altitude'] !== undefined ? data['altitude'] : null,
        data['speed'] !== undefined ? data['speed'] : null,
        data['satellites_visible'] !== undefined ? data['satellites_visible'] : null,
        data['satellites_gps'] !== undefined ? data['satellites_gps'] : null,
        data['satellites_beidou'] !== undefined ? data['satellites_beidou'] : null,
        data['satellites_glonass'] !== undefined ? data['satellites_glonass'] : null,
        data['satellites_galileo'] !== undefined ? data['satellites_galileo'] : null,
        data['satellites_qzss'] !== undefined ? data['satellites_qzss'] : null,
        data['satellites_unknown'] !== undefined ? data['satellites_unknown'] : null,
        data['satellites_used'] !== undefined ? data['satellites_used'] : null,
        data['fix_type'] !== undefined ? data['fix_type'] : null,
        data['fix_status'] !== undefined ? data['fix_status'] : null,
        data['pdop'] !== undefined ? data['pdop'] : null,
        data['hdop'] !== undefined ? data['hdop'] : null,
        data['vdop'] !== undefined ? data['vdop'] : null,
        data['azimuth'] !== undefined ? data['azimuth'] : null,
        data['course'] !== undefined ? data['course'] : null,
        data['status'] !== undefined ? data['status'] : null,
        data['battery_voltage'] !== undefined ? data['battery_voltage'] : null,
        data['external_voltage'] !== undefined ? data['external_voltage'] : null,
        data['gps_fix_mode'] !== undefined ? data['gps_fix_mode'] : null,
        data['modem_app_version'] !== undefined ? data['modem_app_version'] : null,
        data['modem_base_version'] !== undefined ? data['modem_base_version'] : null,
        data['controller_version'] !== undefined ? data['controller_version'] : null,
        data['imei'] !== undefined ? data['imei'] : null,
        data['iccid'] !== undefined ? data['iccid'] : null,
        data['ble_mac'] !== undefined ? data['ble_mac'] : null,
        data['msisdn'] !== undefined ? data['msisdn'] : null,
        data['gsm_status'] !== undefined ? data['gsm_status'] : null,
        data['gps_status'] !== undefined ? data['gps_status'] : null,
        data['gps_ttff_s'] !== undefined ? data['gps_ttff_s'] : null,
        data['imsi'] !== undefined ? data['imsi'] : null,
        data['apn'] !== undefined ? data['apn'] : null,
        data['csq'] !== undefined ? data['csq'] : null,
        data['internal_available_disk_size_bytes'] !== undefined ? data['internal_available_disk_size_bytes'] : null,
        data['external_available_disk_size_bytes'] !== undefined ? data['external_available_disk_size_bytes'] : null,
        data['gps_interval_ms'] !== undefined ? data['gps_interval_ms'] : null,
        data['imu_interval_ms'] !== undefined ? data['imu_interval_ms'] : null,
        data['modem_uptime_ms'] !== undefined ? data['modem_uptime_ms'] : null,
        data['modem_reset_reason'] !== undefined ? data['modem_reset_reason'] : null,
        data['num_logs'] !== undefined ? data['num_logs'] : null,
        data['total_log_size'] !== undefined ? data['total_log_size'] : null,
        data['gps_odometer_m'] !== undefined ? data['gps_odometer_m'] : null,
        data['can_odometer_m'] !== undefined ? data['can_odometer_m'] : null,
        data['rpm_odometer_m'] !== undefined ? data['rpm_odometer_m'] : null,
        data['external_battery_voltage_mv'] !== undefined ? data['external_battery_voltage_mv'] : null,
        data['internal_battery_voltage_mv'] !== undefined ? data['internal_battery_voltage_mv'] : null,
        data['bluetooth_status'] !== undefined ? data['bluetooth_status'] : null,
        data['connected_device_name'] !== undefined ? data['connected_device_name'] : null,
        data['connected_device_mac'] !== undefined ? data['connected_device_mac'] : null,
        data['self_mac_id'] !== undefined ? data['self_mac_id'] : null,
        data['analog_input1_mv'] !== undefined ? data['analog_input1_mv'] : null,
        data['digital_output1_status'] !== undefined ? data['digital_output1_status'] : null,
        data['digital_output2_status'] !== undefined ? data['digital_output2_status'] : null,
        data['digital_input1_status'] !== undefined ? data['digital_input1_status'] : null,
        data['digital_input2_status'] !== undefined ? data['digital_input2_status'] : null,
        data['ignition_status'] !== undefined ? data['ignition_status'] : null,
        data['charging_status'] !== undefined ? data['charging_status'] : null,
        data['controller_uptime_s'] !== undefined ? data['controller_uptime_s'] : null,
        data['controller_reset_reason'] !== undefined ? data['controller_reset_reason'] : null,
        data['controller_reset_reason_unknown_count'] !== undefined ? data['controller_reset_reason_unknown_count'] : null,
        data['controller_reset_reason_wko_count'] !== undefined ? data['controller_reset_reason_wko_count'] : null,
        data['controller_reset_reason_vusb_count'] !== undefined ? data['controller_reset_reason_vusb_count'] : null,
        data['controller_reset_reason_wdt_count'] !== undefined ? data['controller_reset_reason_wdt_count'] : null,
        data['controller_reset_reason_sw_count'] !== undefined ? data['controller_reset_reason_sw_count'] : null,
        data['can_truncated'] !== undefined ? data['can_truncated'] : null,
        data['dbc_crc32'] !== undefined ? data['dbc_crc32'] : null,
        data['VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info'] !== undefined ? data['VECTOR__INDEPENDENT_SIG_MSG_Hazard_Info'] : null,
        data['Battery_Status_SOC'] !== undefined ? data['Battery_Status_SOC'] : null,
        data['Battery_Status_Battery_Status'] !== undefined ? data['Battery_Status_Battery_Status'] : null,
        data['BatteryPack_ProdDate_Production_Day'] !== undefined ? data['BatteryPack_ProdDate_Production_Day'] : null,
        data['BatteryPack_ProdDate_Production_Month'] !== undefined ? data['BatteryPack_ProdDate_Production_Month'] : null,
        data['BatteryPack_ProdDate_Production_Year'] !== undefined ? data['BatteryPack_ProdDate_Production_Year'] : null,
        data['Charging_Status_Realtime_Output_Current'] !== undefined ? data['Charging_Status_Realtime_Output_Current'] : null,
        data['Charging_Status_Realtime_Output_Voltage'] !== undefined ? data['Charging_Status_Realtime_Output_Voltage'] : null,
        data['Battery_Pack_SN_Message_Index'] !== undefined ? data['Battery_Pack_SN_Message_Index'] : null,
        data['Battery_Pack_SN_SN_6'] !== undefined ? data['Battery_Pack_SN_SN_6'] : null,
        data['Battery_Pack_SN_SN_5'] !== undefined ? data['Battery_Pack_SN_SN_5'] : null,
        data['Battery_Pack_SN_SN_4'] !== undefined ? data['Battery_Pack_SN_SN_4'] : null,
        data['Battery_Pack_SN_SN_3'] !== undefined ? data['Battery_Pack_SN_SN_3'] : null,
        data['Battery_Pack_SN_SN_2'] !== undefined ? data['Battery_Pack_SN_SN_2'] : null,
        data['Battery_Pack_SN_SN_1'] !== undefined ? data['Battery_Pack_SN_SN_1'] : null,
        data['Battery_Pack_SN_SN_0'] !== undefined ? data['Battery_Pack_SN_SN_0'] : null,
        data['Charger_Status_Charger_Status'] !== undefined ? data['Charger_Status_Charger_Status'] : null,
        data['Battery_RemainingCapacity_Remaining_time_to_FullCharge'] !== undefined ? data['Battery_RemainingCapacity_Remaining_time_to_FullCharge'] : null,
        data['Battery_RemainingCapacity_Residual_Energy'] !== undefined ? data['Battery_RemainingCapacity_Residual_Energy'] : null,
        data['Battery_RemainingCapacity_ResidualCapacity'] !== undefined ? data['Battery_RemainingCapacity_ResidualCapacity'] : null,
        data['Battery_RemainingCapacity_FullChargeCapacity'] !== undefined ? data['Battery_RemainingCapacity_FullChargeCapacity'] : null,
        data['MCU_SYSINFO_Rated_Max_InputCurrent'] !== undefined ? data['MCU_SYSINFO_Rated_Max_InputCurrent'] : null,
        data['MCU_SYSINFO_Rated_Voltage'] !== undefined ? data['MCU_SYSINFO_Rated_Voltage'] : null,
        data['MCU_SYSINFO_Rated_Speed'] !== undefined ? data['MCU_SYSINFO_Rated_Speed'] : null,
        data['MCU_INFO_MCU_HW_VERSION'] !== undefined ? data['MCU_INFO_MCU_HW_VERSION'] : null,
        data['MCU_INFO_MCU_SW_VERSION'] !== undefined ? data['MCU_INFO_MCU_SW_VERSION'] : null,
        data['MCU_Data_Realtime_Current'] !== undefined ? data['MCU_Data_Realtime_Current'] : null,
        data['MCU_Data_RealTime_Voltage'] !== undefined ? data['MCU_Data_RealTime_Voltage'] : null,
        data['MCU_Data_MotorRPM'] !== undefined ? data['MCU_Data_MotorRPM'] : null,
        data['MCU_Fault_Status_MotorTemperature'] !== undefined ? data['MCU_Fault_Status_MotorTemperature'] : null,
        data['MCU_Fault_Status_ControllerTemp'] !== undefined ? data['MCU_Fault_Status_ControllerTemp'] : null,
        data['MCU_Fault_Status_Braking_Stroke'] !== undefined ? data['MCU_Fault_Status_Braking_Stroke'] : null,
        data['MCU_Fault_Status_Reverse_State'] !== undefined ? data['MCU_Fault_Status_Reverse_State'] : null,
        data['MCU_Fault_Status_CruiseState'] !== undefined ? data['MCU_Fault_Status_CruiseState'] : null,
        data['MCU_Fault_Status_SpeedLimit_Status'] !== undefined ? data['MCU_Fault_Status_SpeedLimit_Status'] : null,
        data['MCU_Fault_Status_Immobilization_Status'] !== undefined ? data['MCU_Fault_Status_Immobilization_Status'] : null,
        data['MCU_Fault_Status_Brake_Status'] !== undefined ? data['MCU_Fault_Status_Brake_Status'] : null,
        data['MCU_Fault_Status_Veh_Mode'] !== undefined ? data['MCU_Fault_Status_Veh_Mode'] : null,
        data['MCU_Fault_Status_Disabled_State'] !== undefined ? data['MCU_Fault_Status_Disabled_State'] : null,
        data['MCU_Fault_Status_Charging_Protection_Status'] !== undefined ? data['MCU_Fault_Status_Charging_Protection_Status'] : null,
        data['MCU_Fault_Status_Ready_Status'] !== undefined ? data['MCU_Fault_Status_Ready_Status'] : null,
        data['MCU_Fault_Status_EBS_Status'] !== undefined ? data['MCU_Fault_Status_EBS_Status'] : null,
        data['MCU_Fault_Status_MotorHall_Failure'] !== undefined ? data['MCU_Fault_Status_MotorHall_Failure'] : null,
        data['MCU_Fault_Status_MotorPhase_failure'] !== undefined ? data['MCU_Fault_Status_MotorPhase_failure'] : null,
        data['MCU_Fault_Status_Overtemp_Fault'] !== undefined ? data['MCU_Fault_Status_Overtemp_Fault'] : null,
        data['MCU_Fault_Status_UnderVoltage_Fault'] !== undefined ? data['MCU_Fault_Status_UnderVoltage_Fault'] : null,
        data['MCU_Fault_Status_OverCurrent_Fault'] !== undefined ? data['MCU_Fault_Status_OverCurrent_Fault'] : null,
        data['MCU_Fault_Status_Driver_Failure'] !== undefined ? data['MCU_Fault_Status_Driver_Failure'] : null,
        data['MCU_Fault_Status_MOSFET_Failure'] !== undefined ? data['MCU_Fault_Status_MOSFET_Failure'] : null,
        data['MCU_Fault_Status_Motor_Controller_RunStatus'] !== undefined ? data['MCU_Fault_Status_Motor_Controller_RunStatus'] : null,
        data['MCU_Fault_Status_Throttle_Failure'] !== undefined ? data['MCU_Fault_Status_Throttle_Failure'] : null,
        data['MCU_Fault_Status_Motor_Overtemp_Fault'] !== undefined ? data['MCU_Fault_Status_Motor_Overtemp_Fault'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Protection_State'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Protection_State'] : null,
        data['Battery_Pack_Fault_Info_Charge_Protection_State'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_Protection_State'] : null,
        data['Battery_Pack_Fault_Info_Severe_OverCell_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Severe_OverCell_Voltage'] : null,
        data['Battery_Pack_Fault_Info_EOL_State'] !== undefined ? data['Battery_Pack_Fault_Info_EOL_State'] : null,
        data['Battery_Pack_Fault_Info_Charge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_MOSDriver_Fail'] : null,
        data['Battery_Pack_Fault_Info_Charge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_Charge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_Discharge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_MOSFail'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_MOSFail'] : null,
        data['Battery_Pack_Fault_Info_ZeroVoltage_Protection'] !== undefined ? data['Battery_Pack_Fault_Info_ZeroVoltage_Protection'] : null,
        data['Battery_Pack_Fault_Info_FullyCharge'] !== undefined ? data['Battery_Pack_Fault_Info_FullyCharge'] : null,
        data['Battery_Pack_Fault_Info_MOS_OverTemp'] !== undefined ? data['Battery_Pack_Fault_Info_MOS_OverTemp'] : null,
        data['Battery_Pack_Fault_Info_OverTemp_Balance_Resistance'] !== undefined ? data['Battery_Pack_Fault_Info_OverTemp_Balance_Resistance'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_Timeout'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_Timeout'] : null,
        data['Battery_Pack_Fault_Info_PreDischarge_OverCurrent'] !== undefined ? data['Battery_Pack_Fault_Info_PreDischarge_OverCurrent'] : null,
        data['Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp'] !== undefined ? data['Battery_Pack_Fault_Info_Predischarge_MOS_OverTemp'] : null,
        data['Battery_Pack_Fault_Info_Temp_Acquisition_Fault'] !== undefined ? data['Battery_Pack_Fault_Info_Temp_Acquisition_Fault'] : null,
        data['Battery_Pack_Fault_Info_Batt_ID_Conflict'] !== undefined ? data['Battery_Pack_Fault_Info_Batt_ID_Conflict'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Plus_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Plus_Current'] : null,
        data['Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Voltage_Acquisition_Fault'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Current'] : null,
        data['Battery_Pack_Fault_Info_Regen_Over_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Regen_Over_Current'] : null,
        data['Battery_Pack_Fault_Info_Charging_OverTemp_Current'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_OverTemp_Current'] : null,
        data['Battery_Pack_Fault_Info_High_Differential_Cell_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_High_Differential_Cell_Temp'] : null,
        data['Battery_Pack_Fault_Info_Charging_Low_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_Low_Temp'] : null,
        data['Battery_Pack_Fault_Info_Charging_Over_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Charging_Over_Temp'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Low_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Low_Temp'] : null,
        data['Battery_Pack_Fault_Info_Discharge_Over_Temp'] !== undefined ? data['Battery_Pack_Fault_Info_Discharge_Over_Temp'] : null,
        data['Battery_Pack_Fault_Info_Pack_Under_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Pack_Under_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Pack_Over_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Pack_Over_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Cell_Under_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Under_Voltage'] : null,
        data['Battery_Pack_Fault_Info_Cell_Over_Voltage'] !== undefined ? data['Battery_Pack_Fault_Info_Cell_Over_Voltage'] : null,
        data['Battery_Pack_Temp_info_Battery_Ambient_Temp'] !== undefined ? data['Battery_Pack_Temp_info_Battery_Ambient_Temp'] : null,
        data['Battery_Pack_Temp_info_Battery_MOS_Temp_Max'] !== undefined ? data['Battery_Pack_Temp_info_Battery_MOS_Temp_Max'] : null,
        data['Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum'] !== undefined ? data['Battery_Pack_Temp_info_Batt_Cell_Temp_Minimum'] : null,
        data['Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum'] !== undefined ? data['Battery_Pack_Temp_info_Batt_Cell_Temp_Maximum'] : null,
        data['Battery_SOC_Info_State_of_Health_SOH'] !== undefined ? data['Battery_SOC_Info_State_of_Health_SOH'] : null,
        data['Battery_SOC_Info_Num_of_Battery_Cycles'] !== undefined ? data['Battery_SOC_Info_Num_of_Battery_Cycles'] : null,
        data['Battery_SOC_Info_State_of_Charge_SOC'] !== undefined ? data['Battery_SOC_Info_State_of_Charge_SOC'] : null,
        data['Battery_Voltage_MOS_Info_ON_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_ON_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_CRG_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_CRG_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_ACC_Signal_Status'] !== undefined ? data['Battery_Voltage_MOS_Info_ACC_Signal_Status'] : null,
        data['Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Batt_PreDischarge_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Charging_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Charging_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Discharge_MOS_State'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Current'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Current'] : null,
        data['Battery_Voltage_MOS_Info_Battery_Voltage'] !== undefined ? data['Battery_Voltage_MOS_Info_Battery_Voltage'] : null,
        data['Battery_Voltage_Current_Info_Remaining_time_to_charge'] !== undefined ? data['Battery_Voltage_Current_Info_Remaining_time_to_charge'] : null,
        data['Battery_Voltage_Current_Info_Total_Battery_Current'] !== undefined ? data['Battery_Voltage_Current_Info_Total_Battery_Current'] : null,
        data['Battery_Voltage_Current_Info_Total_Battery_Voltage'] !== undefined ? data['Battery_Voltage_Current_Info_Total_Battery_Voltage'] : null,
        data['RTC_RTC_seconds'] !== undefined ? data['RTC_RTC_seconds'] : null,
        data['RTC_RTC_Minutes'] !== undefined ? data['RTC_RTC_Minutes'] : null,
        data['RTC_RTC_Hours'] !== undefined ? data['RTC_RTC_Hours'] : null,
        data['RTC_RTC_Days'] !== undefined ? data['RTC_RTC_Days'] : null,
        data['RTC_RTC_Years'] !== undefined ? data['RTC_RTC_Years'] : null,
        data['RTC_RTC_Months'] !== undefined ? data['RTC_RTC_Months'] : null,
        data['Battery_Pack_Temp_Temperature_6'] !== undefined ? data['Battery_Pack_Temp_Temperature_6'] : null,
        data['Battery_Pack_Temp_Temperature_5'] !== undefined ? data['Battery_Pack_Temp_Temperature_5'] : null,
        data['Battery_Pack_Temp_Temperature_4'] !== undefined ? data['Battery_Pack_Temp_Temperature_4'] : null,
        data['Battery_Pack_Temp_Temperature_3'] !== undefined ? data['Battery_Pack_Temp_Temperature_3'] : null,
        data['Battery_Pack_Temp_Temperature_2'] !== undefined ? data['Battery_Pack_Temp_Temperature_2'] : null,
        data['Battery_Pack_Temp_Temperature_1'] !== undefined ? data['Battery_Pack_Temp_Temperature_1'] : null,
        data['Battery_Pack_Temp_Temperature_0'] !== undefined ? data['Battery_Pack_Temp_Temperature_0'] : null,
        data['Battery_Pack_Temp_Number_of_Temperatues'] !== undefined ? data['Battery_Pack_Temp_Number_of_Temperatues'] : null,
        data['Battery_Pack_Temp_Msg_Number_Index'] !== undefined ? data['Battery_Pack_Temp_Msg_Number_Index'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_3_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_2_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_1_4cell'] : null,
        data['Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell'] !== undefined ? data['Cell_Voltage_Info_Cell_Voltage_Indx_0_4cell'] : null,
        data['Cell_Voltage_Info_Num_of_cells'] !== undefined ? data['Cell_Voltage_Info_Num_of_cells'] : null,
        data['Cell_Voltage_Info_Message_Number_Index'] !== undefined ? data['Cell_Voltage_Info_Message_Number_Index'] : null,
        data['Cell_Voltage_Minimum_Voltage'] !== undefined ? data['Cell_Voltage_Minimum_Voltage'] : null,
        data['Cell_Voltage_Maximum_Voltage'] !== undefined ? data['Cell_Voltage_Maximum_Voltage'] : null,
        data['Charge_discharge_Operating_State_Battery7'] !== undefined ? data['Charge_discharge_Operating_State_Battery7'] : null,
        data['Charge_discharge_Opearting_State_Battery6'] !== undefined ? data['Charge_discharge_Opearting_State_Battery6'] : null,
        data['Charge_discharge_Operating_State_Battery5'] !== undefined ? data['Charge_discharge_Operating_State_Battery5'] : null,
        data['Charge_discharge_Operating_state_Battery4'] !== undefined ? data['Charge_discharge_Operating_state_Battery4'] : null,
        data['Charge_discharge_Operating_State_battery3'] !== undefined ? data['Charge_discharge_Operating_State_battery3'] : null,
        data['Charge_discharge_Operating_state_battery2'] !== undefined ? data['Charge_discharge_Operating_state_battery2'] : null,
        data['Charge_discharge_Operating_state_battery1'] !== undefined ? data['Charge_discharge_Operating_state_battery1'] : null,
        data['Charge_discharge_Battery0_Working_State'] !== undefined ? data['Charge_discharge_Battery0_Working_State'] : null,
        data['Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery'] !== undefined ? data['Chg_Dschg_Current_Battery_Pack_Max_Dschg_Current_Battery'] : null,
        data['Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery'] !== undefined ? data['Chg_Dschg_Current_Battery_Pack_Max_Chg_Current_Battery'] : null,
        data['SOP_Info_Battery_Pack_Total_Battery_Discharge_Current'] !== undefined ? data['SOP_Info_Battery_Pack_Total_Battery_Discharge_Current'] : null,
        data['SOP_Info_Battery_Pack_Continuous_Discharge_Current'] !== undefined ? data['SOP_Info_Battery_Pack_Continuous_Discharge_Current'] : null,
        data['SOP_Info_Battery_Pack_Operating_state_Battery4'] !== undefined ? data['SOP_Info_Battery_Pack_Operating_state_Battery4'] : null,
        data['events_dropped'] !== undefined ? data['events_dropped'] : null,
        data['event_timestamp_ms'] !== undefined ? data['event_timestamp_ms'] : null,
        data['event_data_name'] !== undefined ? data['event_data_name'] : null,
        data['event_data_value'] !== undefined ? data['event_data_value'] : null
    ]);

    try {
        const [result] = await pool.query(query, [valuesArray]);
        return result;
    } catch (error) {
        console.error('Error saving telemetry in bulk:', error);
        throw error;
    }
}

async function getBulkData({ imei, startDate, endDate, page = 1, limit = 50 }) {
    let query = 'SELECT * FROM poc_new_bike_telemetry WHERE 1=1';
    const params = [];

    if (imei) {
        query += ' AND imei = ?';
        params.push(imei);
    }
    if (startDate) {
        query += ' AND timestamp >= ?';
        params.push(startDate);
    }
    if (endDate) {
        query += ' AND timestamp <= ?';
        params.push(endDate);
    }

    query += ' ORDER BY timestamp DESC LIMIT ? OFFSET ?';
    const offset = (page - 1) * limit;
    params.push(Number(limit), Number(offset));

    try {
        const [rows] = await pool.query(query, params);
        return rows;
    } catch (error) {
        console.error('Error fetching bulk telemetry data:', error);
        throw error;
    }
}

module.exports = {
    saveTelemetryBulk,
    saveTelemetry,
    isDuplicate,
    getBulkData
};

